### ISSUE TITLE
ReduceConsecutivesTransformer escaping regexes

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/importer#10]
Edited: regex for spaces works, just the escaping of backslash remaining, 

```<reduce>\W</reduce>``` results in ```(\\W)+```

**Comment by essiembre** [comment]
Not sure what you are asking.  [ReduceConsecutivesTransformer](http://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/transformer/impl/ReduceConsecutivesTransformer.html) does not support regular expressions.  ``\W`` is not one of of the "special" characters recognized (which are \r, \n, \t, and \s).

If you want to use regular expressions, look at using [ReplaceTransformer](http://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/transformer/impl/ReplaceTransformer.html) instead.

**Comment by OkkeKlein** [comment]
OK. I guess the special characters made me think this was the case. Closing issue.
