### ISSUE TITLE
Splitting PST Files (Microsoft Exchange format) with DOM splitter

### ISSUE THREAD

**Issue by CorinneKnoe** [Norconex/importer#101]
I am trying to split PST files (contain entire mailboxes) into its elements: emails, attachments, contacts, calendar entries, etc.

Norconex is able to read the PST file, however it returns the entire thing in one file. I tried to use DOM splitter to split the PST into components. So far, no success.

```
<importer>
        
        <preParseHandlers>
        <splitter class="com.norconex.importer.handler.splitter.impl.DOMSplitter"
                        selector=".pst"
                        sourceCharset="UTF-8">
        </splitter>
        </preParseHandlers>
        
        
        <postParseHandlers>
          <tagger class="${tagger}.ReplaceTagger">
            <replace fromField="samplefield" regex="true">
              <fromValue>ping</fromValue><toValue>pongdidididponglalalala</toValue>
            </replace>
            <replace fromField="Subject" regex="true">
				<fromValue>Sample to crawl</fromValue><toValue>Sample crawled</toValue>
			</replace>            
          </tagger>
        </postParseHandlers>
</importer>
```
Is Norconex able to split PST files? Many thanks, Corinne

**Comment by essiembre** [comment]
Hello Corinne,

Yes, the Norconex Importer can split PST files.  Have a look at [GenericDocumentParserFactory](http://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/parser/GenericDocumentParserFactory.html).  You will find many options for controlling exactly what/how you want the split embedded documents.  In its most open form (split every embedded documents), it would look like this:

```xml
<importer>
  <documentParserFactory class="com.norconex.importer.parser.GenericDocumentParserFactory">
    <embedded>
      <splitContentTypes>.*</splitContentTypes>
    </embedded>
  </documentParserFactory>
</importer>
```

You probably want to configure it so it only splits certain content types.

**Comment by CorinneKnoe** [comment]
Thank you very much for your help and the code example. Will give this a try!
