### ISSUE TITLE
Does the Document need to match all restrictTo Tags to "tag" document?

### ISSUE THREAD

**Issue by jshifrin25** [Norconex/importer#102]
I put multiple restrictTo tags in a copyTagger and only the first restriction was adhered to. The other restrictions were ignored. It seems that the code block below is matching any restriction instead of all restrictions. Is that the intended functionality?

``` java
       /**
     * Class to invoke by subclasses to find out if this handler should be
     * rejected or not based on the metadata restriction provided.
     * @param reference document reference
     * @param metadata document metadata.
     * @param parsed if the document was parsed (i.e. imported) already
     * @return <code>true</code> if this handler is applicable to the document
     */
    protected final boolean isApplicable(
            String reference, ImporterMetadata metadata, boolean parsed) {
        if (restrictions.isEmpty()) {
            return true;
        }
        for (PropertyMatcher restriction : restrictions) {
            if (restriction.matches(metadata)) {
                return true;
            }
        }
        if (LOG.isDebugEnabled()) {
            LOG.debug(getClass() + " handler does not apply to: " + reference);
        }
        return false;
    }
```

**Comment by essiembre** [comment]
The expected behavior for restrictTo/onMatch is (taken from javadoc): 

> [...] if one or more filters of type "include" exist in a set of filters, at least one of them must be matched for a document (or other) to be "included". Only one filter of type "exclude" needs to be matched for the document (or other) to be excluded. Filters of type "exclude" have precedence over includes.

Does that answer?
