### ISSUE TITLE
How to crawl an HTML page but not indexing it

### ISSUE THREAD

**Issue by caoyang1211** [Norconex/importer#123]
I would like to crawl an HTML page (seed page), follow the links and index those pages 1 hop from the seed page. But I don't want to index the seed page. How can I implement it? I tried to use the ReferenceFilter under importer/postParseHandlers, like the following:
`<importer>

        <postParseHandlers>
		  <referenceFilters>
			<filter class="ReferenceFilter" onMatch="exclude">
				<valueMatcher method="regex">^.*news/new_files[1-2][0-9][0-9][0-9]\.htm</valueMatcher>
			</filter>
		  </referenceFilters>
        </postParseHandlers>
</importer>` 
But Norconex complains not being able to parse the configuration XML. Any suggestion would be appreciated!

**Comment by essiembre** [comment]
The pre/post Importer handlers expect `<handler>` tags.  In your case, to simply filter on the reference, you can instead use the
[ReferenceFilter](https://opensource.norconex.com/importer/v3/apidocs/com/norconex/importer/handler/filter/impl/ReferenceFilter.html).  I also suggest you use XML CDATA when you start introducing non-alphanumeric characters to avoid surprises and avoid the need for XML character escaping sometimes.  Something like this should do it for you:

```xml
<postParseHandlers>
  <handler class="ReferenceFilter" onMatch="exclude">
    <valueMatcher method="regex"><![CDATA[^.*news/new_files[1-2][0-9][0-9][0-9]\.htm]]></valueMatcher>
  </handler>
</postParseHandlers>

```
