### ISSUE TITLE
Transforming pdftotext parsed text results in concatenated strings

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/importer#16]
Transformation of text results in concatenated strings with pdftotext.

The only difference with PDFBox is that the latter has a whitespace followed by CRLF as EOL and pdftotext doesn't have this whitespace.

However the transformer should transform the CRLF to a whitespace (2 actually).

As this is not happening the output is concatenated,

**Comment by OkkeKlein** [comment]
Better yet, how do you set the replacement to be a whitespace?

Does ```   <toValue> </toValue> ``` even work?

**Comment by OkkeKlein** [comment]
Tested with xml-encoded whitespace ```<toValue>&#032;</toValue>``` and this also did not replace the match with whitespace. A string like "test" however did replace the match.

**Comment by essiembre** [comment]
It turns out the white spaces are not preserved.  After investigation on the XML parser being used, there is a nice feature to turn on or off preserving white paces on a per-tag level.  For instance, this works for me (replace EOL with a space):

```xml
  <replace>
    <fromValue>[\r\n]+</fromValue>
    <toValue xml:space="preserve"> </toValue>
  </replace>
```

**Comment by OkkeKlein** [comment]
Works for me too. Nice catch.

**Comment by essiembre** [comment]
I am marking this as "documentation" and won't close until I update the docs in a few places with this info.

**Comment by essiembre** [comment]
Documented and released.  Closing.
