### ISSUE TITLE
unicode UTF-8 supporting ?

### ISSUE THREAD

**Issue by azimot** [Norconex/importer#18]
importer could to support utf-8 content ?
if yes , have it a special configuration for unicode supporting for example how can i to parse this text ? 
"این یک متن فارسی برای تست است ، ژاله ، گچ ،تشکر"

**Comment by essiembre** [comment]
UTF-8 is the character set used internally by the Importer so it should not cause you trouble.  Can you attach a sample document and explain the issue you have (with steps to reproduce)?

**Comment by essiembre** [comment]
Closing due to lack of details.  Feel free to re-open if you have more details.
