### ISSUE TITLE
bug in com.norconex.importer.handler.tagger.impl.DOMTagger#tagApplicableDocument()

### ISSUE THREAD

**Issue by mrubezhanskyy** [Norconex/importer#21]
Hello,

thank you for doing nice open source software. I found a problem in 

com.norconex.importer.handler.tagger.impl#tagApplicableDocument()

if you configure several dom selectors for a dom tagger, for example
```xml
        <tagger class="com.norconex.importer.handler.tagger.impl.DOMTagger">
            <dom selector="div.address-block span" toField="hoho_address_street" overwrite="false" />
            <dom selector="div.address-block" toField="hoho_address" overwrite="false" />
            <dom selector="div.boolean-listing span" toField="hoho_boolean_labels" overwrite="false" />
```

and one of these selectors does not find anything, then other not evaluated selectors  are just ignored. The problem is here:

```java
            for (DOMExtractDetails details : extractions) {
                Elements elms = doc.select(details.selector);
                // no elements matching
                if (elms.isEmpty()) {
                    return;
                }
...
...
                if (values.isEmpty()) {
                    return;
                }
```

instead of "return" you should code "continue"

Kind regads

Mike

**Comment by essiembre** [comment]
Thanks for reporting this issue and troubleshooting it!   I have made a fix which is now available in the latest 2.5.3-SNAPSHOT importer [snapshot release](https://www.norconex.com/collectors/importer/download).

Replace the ``norconex-importer-xxx.jar`` you currently have under the "lib" directory of your installation with the JAR from the snapshot version.

Please confirm.
