### ISSUE TITLE
Launch the Transformer without an Importer

### ISSUE THREAD

**Issue by AntonioAmore** [Norconex/importer#3]
To skip costly launch of the collector-http, I'd like to create a kind of test project and try there different transformation strategies.

I created a class inside the same namespace, as the Transformer's and have problems with launch of ```transformTextDocument(...)``` method.

```java
public class MyDocumentTransformer extends AbstractCharStreamTransformer ... 
...
public class TestClass {
...
        MyDocumentTransformer transformer = new MyDocumentTransformer();
        transformer.loadHandlerFromXML(configuration);
        transformer.transformTextDocument(param1, param2, param3, param4, param5);
```

I'd like to know what to set as the method's parameters, as docs tells only about types, but not about semantics.

**Comment by essiembre** [comment]
My recommendation would be to create yourself unit tests using JUnit.   You can look for examples in the project itself.   For example, [here](https://github.com/Norconex/importer/tree/master/norconex-importer/src/test/java/com/norconex/importer/handler/transformer/impl) are example transformer unit tests.

**Comment by essiembre** [comment]
Are you OK with the sample(s)?

**Comment by AntonioAmore** [comment]
Sorry for delay. 

It's a pity but I'm not kin with unit tests, so I solved the issue with more rough approach.

**Comment by essiembre** [comment]
Glad to hear you found a solution.  I'll consider this issue closed then.
