### ISSUE TITLE
Can't get DebugTagger to produce any output

### ISSUE THREAD

**Issue by pcolmer** [Norconex/importer#30]
I've got the following as my crawler configuration:

    <crawlers>
      <crawler id="Wiki Crawler">
        <startURLs stayOnDomain="true">
          <url>http://wiki.linaro.org/</url>
        </startURLs>
        #parse("shared/importer-config.xml")

        <importer>
          <postParseHandlers>
            <tagger class="com.norconex.importer.handler.tagger.impl.RenameTagger">
              <rename fromField="document.contentEncoding" toField="content_encoding" overwrite="true" />
              <rename fromField="document.contentType" toField="content_type" overwrite="true" />
            </tagger>
            <tagger class="com.norconex.importer.handler.tagger.impl.DebugTagger"
                logContent="true" >
            </tagger>
          </postParseHandlers>
        </importer>
      </crawler>
    </crawlers>

When I run the code, though, nothing appears in the output from the DebugTagger. 

log4j is set to have the main output on DEBUG:

    log4j.logger.com.norconex.collector.http=DEBUG
    log4j.logger.com.norconex.collector.core=DEBUG
    log4j.logger.com.norconex.importer=DEBUG
    log4j.logger.com.norconex.committer=DEBUG

The documentation for DebugTagger says the list of fields is optional, so I'm expecting everything to get dumped in the output/log, but I'm not seeing anything.

**Comment by essiembre** [comment]
What is the content of "shared/importer-config.xml"?  The file name suggests an ``<importer>`` section. If so, that means you probably have 2 ``<importer>`` section so the second one is ignored (the one with DebugTagger in it).  Please confirm.

**Comment by pcolmer** [comment]
Thanks for spotting that! That will teach me to re-use one of the examples without fully understanding it :)

Just a suggestion: perhaps the code could emit a warning if there are multiple sections encountered and only one is supported?

Removing the included content does indeed get my bits working.

**Comment by essiembre** [comment]
Glad it is working now.  As for being notified when the config is invalid, there is currently a feature request for this, which you can track here: #27.
