### ISSUE TITLE
FeatureRequest: MergeTagger

### ISSUE THREAD

**Issue by liar666** [Norconex/importer#32]
Hi,

For complicated reasons, I need a MergeTagger, that would take arguments: fromField1, fromField2, toField, separator and merge/concatenate value-by-value the contents of sourceField1+sourceField2 into destinationField with optional separation with separator).

Example:
EXP_FIRST_NAME=Fabien^|~Albert
EXP_LAST_NAME=Coco^|~Rico
-- separator=" "-->
EXP_NAME=Fabien Coco^|~Albert Rico

I'm currently trying to write my own quick&dirty version, but norconex's importer you would probably benefit from directly including a clean a generic version!

In case number of values in the fromFields differs, it could raise an exception or accept a default value?

The prototype of the configuration would be:
```
 <tagger class="com.norconex.importer.handler.tagger.impl.MergeTagger">
      <merge fromField1="sourceFieldName" fromField2="sourceFieldName" toField="targetFieldName" separator="sep">
      </merge>
 </tagger>
```

**Comment by liar666** [comment]
Here's a rough draft of my code... Seems to be working, but far from clean/complete :) You're welcome to re-use it!

[MergeTagger.txt](https://github.com/Norconex/importer/files/459597/MergeTagger.txt)

**Comment by essiembre** [comment]
Thanks for sharing!
