### ISSUE TITLE
ReduceConsecutivesTransformer behavior

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/importer#33]
My parsed content has a lot of CRLF I am trying to clean up. Should
```
<reduce>\r</reduce>
<reduce>\r\n</reduce>
<reduce>\n</reduce>
```
be working or is the \r\n not supported?

**Comment by essiembre** [comment]
What is the parent tag for these reduce tags?  Assuming it is ``<transformer class="com.norconex.importer.handler.transformer.impl.ReduceConsecutivesTransformer" ...>`` then yes it should work.

Can you attach a sample document and the entire transformer config snippet?

**Comment by OkkeKlein** [comment]
My guess is this didn't work because the regex would have to be multiline or something. I fixed it by transforming /n and /r to whitespace and then do a reduce with \s.

Works for me.

**Comment by svanschalkwyk** [comment]
I tried Okke's implementation without success. 
Is there a special implementaion of regex of which I should be aware?
