### ISSUE TITLE
using ScriptTransformer with a tagged field

### ISSUE THREAD

**Issue by angelo337** [Norconex/importer#34]
hi there
I am having an issue with a transformation I am trying to put in place

after I capture some information from the content field like this:

```xml
<pattern field="consorcios_UT" >
  ((([U|u](NION|nion)\s[T|t](EMPORAL|emporal))|([C|c](ONSORCIO|onsorcio)))\s)+(([A-Z][\p{L}]*[\p{S}]*)+\s)
</pattern>
```

I am trying to use this field (consorcios_UT) in a script like this:
```xml
<transformer class="com.norconex.importer.handler.transformer.impl.ScriptTransformer">
    <script><![CDATA[
        consorcios_UT = consorcios_UT.replace(/consorcio/g, 'consorcio');
        /*return*/ consorcios_UT;
        ]]></script>
</transformer>
```
but I get and error saying that is not such a field as  "consorcios_UT" defined.

my question how should I process a field that is just created in order to normalize all information and avoid case miss match or strip spaces or punctuation signs?

thanks a lot
angelo

**Comment by essiembre** [comment]
The message is accurate, "consorcios_UT" is not a variable.  Refer to the [ScriptTransformer](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/transformer/impl/ScriptTransformer.html) documentation to find out what variables are made available.   In your case, you have to grab your value from the "metadata" variable.  Usage could look like this:
```
// to obtain a field value:
consorcios_UT = metadata.getString('consorcios_UT');

// do what you need with your variable here

// to store a new field value:
metadata.setString('consorcios_UT', consorcios_UT);
```

Also, there might be chances you can use existing tagger classes to do what you want without having to use scripting.  For instance, to do a search and replace on a field, you can use the [ReplaceTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/ReplaceTagger.html).

**Comment by angelo337** [comment]
thanks a lot for your help, It's working now I am on the right track to test my corpus
best regards
