### ISSUE TITLE
file size limit

### ISSUE THREAD

**Issue by angelo337** [Norconex/importer#51]
hi there
I have a question regarding the importer, Is it possible to limit the content size of a File, I am having issues with a some large files in MS-Excel, and I would like to just index a couple first MB instead of the 45MB os the full file.

could you please point me out some resource or give me some clues how to deal with that large files?
thanks a lot
best regards
angelo

**Comment by essiembre** [comment]
The simplest is probably to use the [SubstringTransformer](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/transformer/impl/SubstringTransformer.html) as a post-parse handler.
```xml
<transformer class="com.norconex.importer.handler.transformer.impl.SubstringTransformer"
          end="10000"/>
```

The above example will truncate after the 10,000 character (exclusive).

Does that work for you?

**Comment by angelo337** [comment]
thanks a lot for your fast answer, I will try it and let you know
