### ISSUE TITLE
Create a document tagger that extract both field values and names.

### ISSUE THREAD

**Issue by essiembre** [Norconex/importer#52]
Create a tagger that allows extracting both the field names and field values as pairs. 

The following is a use case describing the requirement, reported here: https://github.com/Norconex/collector-http/issues/372#issuecomment-322978476.

Assume the following in a page:
```html
<div class="field">First Name</div>
<div class="value">Joe</div>
<div class="field">Last Name</div>
<div class="value">Dalton</div>
```

The tagger should be able to extract these fields:

```
First Name = Joe
Last Name = Dalton
```

**Comment by essiembre** [comment]
This feature is now available in latest importer [snapshot release](https://www.norconex.com/collectors/importer/download).

The [TextPatternTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/TextPatternTagger.html) now supports an optional ``fieldGroup`` attribute that tells which regular expression match group to use for the field name.  For instance, the above use case can be addressed like this:
```xml
  <preParseHandlers>
    <tagger class="com.norconex.importer.handler.tagger.impl.TextPatternTagger" >
      <pattern fieldGroup="1" valueGroup="2"><![CDATA[
        <div.*?class="field".*?>(.*?)</div>.*?<div.*?class="value">(.*?)</div>
      ]]></pattern>
    </tagger>  
  </preParseHandlers>
```

@akshaybijawe and/or @OkkeKlein, can you please test and confirm (as this new option should address both https://github.com/Norconex/collector-http/issues/372 and #54)?

For command-line usage, I recommend you use the install script since there might be other jars updated in the process.

**Comment by OkkeKlein** [comment]
I tested it and it works.

**Comment by essiembre** [comment]
Great, thanks!

**Comment by fleitonSearch** [comment]
Hi Pascal,
I'm trying to run it but I'm getting this error:

`ERROR (XML Validation) TextPatternTagger: cvc-complex-type.3.2.2: Attribute 'fieldGroup' is not allowed to appear in element 'pattern'.
ERROR [XMLConfigurationUtil$LogErrorHandler] (XML Validation) TextPatternTagger: cvc-complex-type.3.2.2: Attribute 'fieldGroup' is not allowed to appear in element 'pattern'.
ERROR (XML Validation) TextPatternTagger: cvc-complex-type.3.2.2: Attribute 'valueGroup' is not allowed to appear in element 'pattern'.
ERROR [XMLConfigurationUtil$LogErrorHandler] (XML Validation) TextPatternTagger: cvc-complex-type.3.2.2: Attribute 'valueGroup' is not allowed to appear in element 'pattern'.
ERROR (XML Validation) TextPatternTagger: cvc-complex-type.4: Attribute 'field' must appear on element 'pattern'.
ERROR [XMLConfigurationUtil$LogErrorHandler] (XML Validation) TextPatternTagger: cvc-complex-type.4: Attribute 'field' must appear on element 'pattern'.
There were 3 XML configuration error(s).`

And this is my config file.
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>


<httpcollector id="Minimum Config HTTP Collector">

  
  <progressDir>./examples-output/clinicalWebsiteRegex/progress</progressDir>
  <logsDir>./examples-output/clinicalWebsiteRegex/logs</logsDir>

  <crawlerDefaults>

    <numThreads>2</numThreads>
    <maxDepth>0</maxDepth>
    <workDir>$workdir</workDir>
    <orphansStrategy>DELETE</orphansStrategy>

  </crawlerDefaults>

  <crawlers>
    <crawler id="Norconex Minimum Test Page">

      
      <startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
        <url>https://clinicaltrials.gov/ct2/show/NCT00000102</url>
      </startURLs>

      

      
      <workDir>./examples-output/clinicalWebsiteRegex</workDir>

      
      <maxDepth>1</maxDepth>

      
      <sitemapResolverFactory ignore="true" />

      
      <delay default="5000" />

      <importer>
        <preParseHandlers>
          <tagger class="com.norconex.importer.handler.tagger.impl.TextPatternTagger" >
            <pattern fieldGroup="1" valueGroup="2">
                     <![CDATA[
                          <div.*?class="info-title".*?>(.*?)</div>.*?<div.*?class="info-text">(.*?)</div>
                     ]]>              
            </pattern>
          </tagger>  
        </preParseHandlers>
      </importer>

        
      <committer class="com.norconex.committer.core.impl.XMLFileCommitter">
        <directory>./examples-output/clinicalWebsiteRegex</directory>
        <pretty>true</pretty>
        <docsPerFile>1</docsPerFile>
        <compress>false</compress>
        <splitAddDelete>false</splitAddDelete>
      </committer>


    </crawler>
  </crawlers>

</httpcollector>`

I'm using the snapshot version as you mentioned.

Any idea?

**Comment by fleitonSearch** [comment]
Forget it. Just found the solution. The solution is to have the importer tag outside the crawler tag.

**Comment by essiembre** [comment]
I just downloaded it and do not see this problem.  Did you download the **importer** snapshot (and not a Collector).  Also, did you run the install script?   Maybe you have two versions of the importer in your classpath and the older one gets picked up?  Look in the "lib" folder for ``norconex-importer-*``.

**Comment by fleitonSearch** [comment]
It worked fine I was doing the install in the wrong path. Sorry about that. Thanks! :)
