### ISSUE TITLE
ReplaceTagger and spaces in toField

### ISSUE THREAD

**Issue by liar666** [Norconex/importer#56]
Hi,

I was trying to replace "&nbsp" (bad HTML tag extracted from the page I was crawling) with a " " with ReplaceTagger, I fought with the code not inserting the space.

I just found that the following is working:
```
<toValue xml:space="preserve"> </toValue>
```
in the doc of ReplaceTransformer:
https://www.norconex.com/collectors/importer/latest/apidocs/index.html?com/norconex/importer/handler/transformer/impl/ReplaceTransformer.html
Would be great to document that option in ReplaceTagger's doc:
https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/ReplaceTagger.html

**Comment by essiembre** [comment]
Done.

FYI, the ``xml:space`` attribute is defined in the XML Standard so it is not specific to the Importer XML configuration.  This means you should be able to use this attribute anywhere in your config.
