### ISSUE TITLE
DOMTagger and <head><script>

### ISSUE THREAD

**Issue by liar666** [Norconex/importer#57]
On the page:
https://web-ast.dsi.cnrs.fr/l3c/owa/personnel.infos_admin?p_numero_sel=1361736
If I use a crawler with:
```
          <tagger class="com.norconex.importer.handler.tagger.impl.DOMTagger">
            <dom selector="head script:eq(2)" toField="SCRIPT-HTML"
                 overwrite="true"
                 extract="outerHtml" />  <!-- diff -->
            <dom selector="head script:eq(2)" toField="SCRIPT-TEXT"
                 overwrite="true"
                 extract="text" /> <!-- diff -->
         </tagger>
```

I get the correct HTML code in SCRIPT-HTML, but nothing in SCRIPT-TEXT. Is that OK?

**Comment by essiembre** [comment]
``<script>`` content is considered data, not text.  So changing ``text`` for ``data`` will do it.

**Comment by liar666** [comment]
OK. Thanks. I never noticed how big has the list of "extract options" has grown :)
https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/DOMTagger.html
