### ISSUE TITLE
DOMSplitter and wrong ContentType

### ISSUE THREAD

**Issue by sveba** [Norconex/importer#58]
I'm splitting documents with the DOMSplitter and all works great. The only problem that I have is that sometimes the DOMSplitter creates the childDoc with wrong content type `text/plain` which results in having html tags in my content. 

Maybe a solution would be to have the possibility to put explicit ContentType in the configuration. Or using the ContentType of the parent (in my case `text/html;charset=UTF-8`)

**Comment by essiembre** [comment]
Can you provide a sample to reproduce?

**Comment by sveba** [comment]
I would gladly  do that, but the content is not public yet.

Something that maybe can help is that the parent URL doesn't end with `*html`, only with `\`
The response headers include `ContentType`-Header with the right value.

**Comment by essiembre** [comment]
Sorry, but I cannot reproduce with my own tests (it is working as expected).   Can you attach your config with a sample HTML document causing the problem?  If too sensitive, you can email me those documents, referencing this ticket.

**Comment by essiembre** [comment]
@sveba any update?

**Comment by sveba** [comment]
@essiembre sorry, but I am not allowed to send you any code and the samples that I create are working fine also for me. So I guess you can close this one
