### ISSUE TITLE
Unable to import tagValues in AWS Cloudsearch

### ISSUE THREAD

**Issue by umeshkalia** [Norconex/importer#59]
I am trying to crawl web pages to store in AWS Cloud Search and facing problem in storing tags value in cloudsearch. 
Below are details of problem:

I am able to see both title and h3 in Debug LOG. 
**Value of "title" is being successfully imported in AWS cloudsearch, but contents of "h3" are not being added in AWS cloudsearch.**

I am always deleting committer-queue and crawler folders everytime before I run http-collector.

Below is the import configuration used by me:
```
<importer>
<preParseHandlers>
         <tagger class="com.norconex.importer.handler.tagger.impl.DOMTagger">
      <dom selector="h3" toField="h3" overwrite="true" defaultValue="Nil"/>  
       </tagger>
    <tagger class="com.norconex.importer.handler.tagger.impl.DebugTagger"
           logFields="h3"   logLevel="INFO">
          </tagger>
</preParseHandlers>
        <postParseHandlers>
         <tagger class="com.norconex.importer.handler.tagger.impl.KeepOnlyTagger">
            <fields>title,description,content,popularity</fields>
          </tagger>
          <tagger class="com.norconex.importer.handler.tagger.impl.DebugTagger"
           logFields="title"   logLevel="INFO">
          </tagger>
        </postParseHandlers>
      </importer> 
```
Debug LOG is:
![image](https://user-images.githubusercontent.com/1909249/29757549-42530238-8bca-11e7-8060-b1470c19f116.png)

Please suggest solution asap.

**Comment by essiembre** [comment]
On first glance, I see nothing wrong.   What does AWS Cloud search tells you when you try to add this document?  Any indication in CloudSearch logs?

Have you tried adding the ``h3`` field to your SolrCloud schema before indexing?

**Comment by umeshkalia** [comment]
Thanks for your reply.

I had already resolved it by adding "h3" in POSTPARSEHANDLER section (as shown below).

![image](https://user-images.githubusercontent.com/1909249/29804081-b92c3e14-8c9d-11e7-917e-5ed191da68b6.png)
