### ISSUE TITLE
Wrong class name in example

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/importer#6]
The example at http://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/ForceSingleValueTagger.html should show
```
<tagger class="com.norconex.importer.handler.tagger.impl.ForceSingleValueTagger">

instead of

<tagger class="com.norconex.importer.handler.tagger.impl.SingleValueTagger">
```

**Comment by essiembre** [comment]
Fixed. Thanks for reporting!
