### ISSUE TITLE
Feature Request:  ExternalTagger for content and existing metadata

### ISSUE THREAD

**Issue by jmrichardson** [Norconex/importer#64]
Hi,

I am requesting (actually begging :) ) for an ExternalTagger to be able to create new metadata fields using the document content and metadata (such as document.reference).  The idea is to be able to have an external application process the content and metadata, then output the new metadata fields to STDOUT.  The content and existing metadata would not be changed.  Please see #63 .

Thank you for your consideration.

**Comment by essiembre** [comment]
Considered.  It will be done.

**Comment by jmrichardson** [comment]
Yay!  Thank you and looking forward to implementing it :)

**Comment by essiembre** [comment]
A new [ExternalTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/ExternalTagger.html) is now part of the latest snapshot release.

Please give it a try and confirm it works as expected.

**Comment by jmrichardson** [comment]
Thank you for implementing this feature!  I ran into an issue with spaces in the $REFERENCE in the document file name:

```
<tagger class="com.norconex.importer.handler.tagger.impl.ExternalTagger" >
            <command>/home/es/elastic/ingest/tag/tagger.R "${REFERENCE}"</command>
</tagger>
```
For a file such as the following:

> /data/PMFiles/xxxx/APPEAL/Supreme Court of Kentucky - Movants Motion to Supplement Authortieis.pdf

The first argument seen by the "tagger.R" app is:

> /data/PMFiles/xxxx/APPEAL/Supreme

I have tried enclosing $REFERENCE with " as above and also with '

Perhaps the importer is stripping the quotes prior to sending to tagger.R?

Also, one minor documentation update, you may want to change "[TaggerTransformer](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/ExternalTagger.html)" to "ExternalTagger" in the below:

```
  <tagger class="com.norconex.importer.handler.tagger.impl.TaggerTransformer" >
      <command>/path/tag/app ${INPUT} ${OUTPUT_META}</command>
  </tagger>
```

**Comment by essiembre** [comment]
This will need further investigating, but in the meantime, maybe you can define a custom replace pattern using the GenericURLNormalizer to escape white spaces with a ``^`` character for windows or a ``\`` on other OSes.

**Comment by jmrichardson** [comment]
Hi, I am not sure that I can use the GenericURLNormalizer as I am using the filesystem collector and not the HTTP collector.  At least, I can't find it's usage in the [importer ](https://www.norconex.com/collectors/importer/configuration)documentation.  I did try the ScriptTagger in <postParseHandlers> and <preParseHandlers> but it appears not to take affect as I believe the ${REFERENCE} being sent in the ExternalTagger is not modified (even though it is modified before being sent to ES).  I did make sure the document.reference modification happens before the ExternalTagger in my config.xml.   Perhaps the pre and post handlers happen after the ${REFERENCE} field is assigned its value?  Here is a snip of my config.xml with document.reference being encoded:

```
 <importer>
        <parseErrorsSaveDir>/home/es/elastic/ingest/norconex/workdir/errors</parseErrorsSaveDir>

        <postParseHandlers>

          <tagger class="com.norconex.importer.handler.tagger.impl.ScriptTagger">
            <script><![CDATA[

              metadata.setString('document.reference',
              encodeURL(metadata.getString('document.reference')));

            ]]></script>
          </tagger>

          <tagger class="com.norconex.importer.handler.tagger.impl.ExternalTagger" >
            <command>/home/es/elastic/ingest/tag/tagger.R ${REFERENCE}</command>
            <metadata
               outputFormat="properties">
            </metadata>
          </tagger>


        </postParseHandlers>
      </importer>
```

However, it is being sent unencoded to tagger.R but encoded to ES.  

Thanks for your help.  John

**Comment by essiembre** [comment]
I am a bit short on time these days but a fix is being worked on.  In the meantime, if you do not mind coding a little, you can check out  [IFileDocumentProcessor](https://www.norconex.com/collectors/collector-filesystem/latest/apidocs/com/norconex/collector/fs/doc/IFileDocumentProcessor.html).  It allows you to make changes to the java "document" object you normally can't access directly.  You set it up in your crawler config:
```xml
            <preImportProcessors>
                <processor class="..." />
                ...
            </preImportProcessors>
```

Maybe this can help.

**Comment by essiembre** [comment]
I was able to reproduce and I provided a fix in the latest snapshot.  Now arguments with spaces should be handled properly (keep your double-quotes in your command).  My own tests were OK, but please have a try and let me know.

**Comment by jmrichardson** [comment]
THANK YOU!  It works! :) I really appreciate your time implementing this feature.  I will keep you posted on any other issues.  This software is really amazing!  Thanks again.
