### ISSUE TITLE
TextPatternTagger issue

### ISSUE THREAD

**Issue by aleha84** [Norconex/importer#65]
As suggested in [DOMtagger description](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/DOMTagger.html) it is better (in performance purposes) to use TextPatternTagger. 

Most of the pages have a breadcrumb which i need to store in metadata field.  Page markup is like this:
```
<div class="blocks-list__item hidden-xs">
                                                <div class="row">
                                                    <div class="col-sm-28"><ol class="breadcrumb">
<li><a href="/ru/"><span class="breadcrumb__home"></span></a></li> 
<li><a href="/s4">Рынки</a></li>
<li><a href="/ru/derivatives/">Срочный рынок</a></li>
<li><a href="/ru/members.aspx?tid=35">Участники</a></li>
<li><a href="/ru/derivatives/open-positions.aspx">Информация об открытых позициях</a></li>
</ol></div>
                                                    
                                                </div>
                                            </div>
```

In importer.preParseHandlers added two sections:

```
<tagger class="com.norconex.importer.handler.tagger.impl.DOMTagger">
	<restrictTo caseSensitive="false" field="content-Type">
		text/.*
	</restrictTo>
	<dom selector="ol.breadcrumb" toField="nav-breadcrumb-dom" extract="outerHtml" />
</tagger>
<tagger class="com.norconex.importer.handler.tagger.impl.TextPatternTagger" >
	<pattern field="nav-breadcrumb" caseSensitive="false">
		<![CDATA[<ol class="breadcrumb">(.*)</ol>]]>
	</pattern>
</tagger>
```

DOMTagger - works fine.
TextPatternTagger - found nothing. 

Is my confing wrong?

**Comment by essiembre** [comment]
I just tried your config snippet with your sample content and it worked fine for me.  Which version are you using?  You can try the latest snapshot in case something was fixed.  Also, are you using any transformers before invoking the TextPatternTagger?  Maybe the HTML is slightly modified beforehand?

Unless you are already facing performance issues, I suggest you use whatever approach you are more comfortable with.  Unless your CPUs are maxed out, you can increase the number of threads and reduce the default delay.  This should have a bigger performance impact than switching from DOMTagger to TextPatternTagger.

**Comment by aleha84** [comment]
Importer used latest stable. No transformers before. 
There is no performance slowdown was detected, so i keep using DOMTagger. 
Thanx.
