### ISSUE TITLE
array field return when carriage return \n

### ISSUE THREAD

**Issue by angelo337** [Norconex/importer#69]
hi there Pascal
I am having an issue with the imported and field returns from an external content, all the HTML returned is format in every line with "\n" and my custom field is returning not a single string but an array of values.
Could you please help me ?
thanks

**Comment by angelo337** [comment]
in order to convert an array to a single string we can use:

`  <tagger class="com.norconex.importer.handler.tagger.impl.ForceSingleValueTagger">
      <singleValue field="content_ascii_txt" action="mergeWith: "/>
  </tagger>`

with that configuration we can join the array using a single space " ", however if you need another character you can replace it with your character after ':'

**Comment by essiembre** [comment]
Glad you found a way and took the time to report it.
