### ISSUE TITLE
Restricting ReplaceTransformer

### ISSUE THREAD

**Issue by essiembre** [Norconex/importer#7]
From @OkkeKlein, originally submitted at https://github.com/Norconex/collector-http/issues/89:
> The regex in <restrictTo caseSensitive="false" field="document.reference">.*test.*</restrictTo> is never passed to the importerhandler. Only field value.

**Comment by essiembre** [comment]
Fix available in latest [snapshot release](http://www.norconex.com/collectors/importer/download).

**Comment by OkkeKlein** [comment]
Works for me. Thank you for quick fix!

**Comment by essiembre** [comment]
The fix is in the new [Importer 2.2.0 stable release](http://www.norconex.com/collectors/importer/download).
