### ISSUE TITLE
RenameTagger doesn't seem to be working

### ISSUE THREAD

**Issue by jacksonp2008** [Norconex/importer#70]
Trying to rename a field, but doesn't seem to work for me.  The original "title" field is still in the data.

I tried both <prePars...  as well as <postParse...  Unclear on what the difference would between pre/post.

```
      <importer>
      <preParseHandlers>
  <tagger class="com.norconex.importer.handler.tagger.impl.RenameTagger">
      <rename fromField="title" toField="upd_title" overwrite="true" />
  </tagger>
        </preParseHandlers>
      </importer>
```

You can see "title" still in the data with kibana.
![screen shot 2017-11-17 at 14 53 52](https://user-images.githubusercontent.com/1813327/32972657-4196b952-cba8-11e7-91ce-66bf88dd930b.png)

**Comment by essiembre** [comment]
It is possible that a title is added again when parsing occurs.  To confirm whether the field is really renamed properly, I recommend you place a [DebugTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/DebugTagger.html) before and after your RenameTagger and you will see what you have before and after.  E.g. this one will log your two fields using the log level INFO:
```xml
<tagger class="com.norconex.importer.handler.tagger.impl.DebugTagger"
          logFields="title,upd_title" logLevel="INFO" >
```

**Comment by jacksonp2008** [comment]
Debug is the key, working well now.

thankyou!
