### ISSUE TITLE
REJECTED_IMPORT: why exactly?

### ISSUE THREAD

**Issue by ronjakoi** [Norconex/importer#77]
Is there a way to find out why exactly the import was rejected on a document? Would adjusting logging levels help?

In case there isn't a way, I would like to submit a feature request to allow logging which filter instruction caused the document to be rejected.

**Comment by essiembre** [comment]
The logging level is indeed where it happens. Use DEBUG in log4j.properties.

Are you using the importer with a Collector? If so, you can control which type of rejections you would like to get more info with DEBUG for crawler events starting with REJECTED... For example:
```
log4j.logger.CrawlerEvent.REJECTED_IMPORT=DEBUG
log4j.logger.CrawlerEvent.REJECTED_FILTER=DEBUG
log4j.logger.CrawlerEvent.REJECTED_NOTFOUND=DEBUG
log4j.logger.CrawlerEvent.REJECTED_BAD_STATUS=DEBUG
log4j.logger.CrawlerEvent.REJECTED_ERROR=DEBUG
log4j.logger.CrawlerEvent.REJECTED_REDIRECTED=DEBUG
...
```

The first one is for import-related rejections.
