### ISSUE TITLE
TitleGeneratorTagger for non-English text

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/importer#8]
Was testing usability of output and noticed  "Performing monolingual clustering in: English". Documentation said multiple languages were supported. Are they auto-detected?

Is there a way to override Carrot's clustering algorithm? Use custom stopwords?

I doubt the quality will ever be usable for titles, but it could be interesting to add as keywords.

**Comment by essiembre** [comment]
Yes, I believe supported languages are detected by Carrot.  

Carrot can probably be tweaked to be better in some cases, but to use something else right now, you would need to create your own tagger.  

If the general feedback we get is the titles are simply no good most of the time, we may consider taking this carrot-based approach out altogether (ideally replacing it with something else).  That would eliminate a few library dependencies as well.

**Comment by OkkeKlein** [comment]
Autodetection doesn't seem to work.

For PDF's that never got a proper title it might be useful to use Carrot, but for other content it is probably just a nice tool to find relevant keywords. Kind of like the interesting terms of MLT in Solr. 

To improve the quality you probably have to tweak and tune a lot. And with different settings per content domain.

I don't need this feature atm, but I'm always willing to test code.

**Comment by OkkeKlein** [comment]
TitleGeneratorTagger was re-written no longer uses Carrot, to reduce library dependencies.

This makes issue obsolete. Closing.
