### ISSUE TITLE
Is it possible to use multiple stripAfterRegex in StripAfterTransformer

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/importer#84]
Can there be multiple `<stripAfterRegex>` tags like ` <stripBetween>`?

**Comment by OkkeKlein** [comment]
Doesn't seem to be possible.

**Comment by essiembre** [comment]
FYI, since it takes regex, you can have your multiple patterns together, like: 
```
(pattern1|pattern2|pattern3)
```
If you want more control, you can also use ReplaceTransformer (which supports multiple entries).
