### ISSUE TITLE
DomTagger does not respect overwrite=true

### ISSUE THREAD

**Issue by ohtwadi** [Norconex/importer#90]
Hello,

I wanted to set the title to a specific div, but noticed that using the DOMTagger with overwrite="true" actually appends the new value to the existing value in title field.

```xml
<preParseHandlers>
  <tagger class="com.norconex.importer.handler.tagger.impl.DOMTagger">
    <dom selector="div#ArticleDetailTitle" toField="title" overwrite="true"/>
  </tagger>
</preParseHandlers>
```

I'm working around this by copying to a temp field and then copying that temp field to the actual title field. CopyTagger respects overwrite=true just fine.

```xml
<postParseHandlers>
  <tagger class="com.norconex.importer.handler.tagger.impl.DOMTagger">
    <dom selector="div#ArticleDetailTitle" toField="title-temp" overwrite="true"/>
  </tagger>

  <tagger class="com.norconex.importer.handler.tagger.impl.CopyTagger">
    <copy fromField="title-temp"	toField="title" overwrite="true" />
  </tagger>
</postParseHandlers>
```

- H

**Comment by essiembre** [comment]
I suspect it works, but a title gets added when the document is parsed and a title is extracted (adding to the one you created with DOMTagger.  Your workaround is a good one, or you can also look at [ForceSingleValueTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/ForceSingleValueTagger.html) as a post-parse handler.
