### ISSUE TITLE
SplitTagger Retains original String [Importer 2.9.0]

### ISSUE THREAD

**Issue by jshifrin25** [Norconex/importer#97]
I would like to use the SplitTagger to replace a metadata field as multiple values and remove the original comma delimited string. Currently, the SplitTagger appends the array of strings to a list containing the original String. I would like there to be an option to remove the original string from the list.

**Comment by essiembre** [comment]
I cannot reproduce.  Which version are you using? Can you send me a sample config that has the minimum settings to reproduce your issue?

**Comment by essiembre** [comment]
I tried reproducing again without success.  Can you please attach an HTML causing the issue for you?
